### ISSUE TITLE
Docs not being indexed

### ISSUE THREAD

**Issue by akosma** [atg/Ingredients#8]
Final problem of my Instruments trilogy :)
The app launches, it offers me to play tic-tac-toe, but no indexing happens. Ever.
I've had to reinstall the app several times to get it to work properly.

**Comment by atg** [comment]
Yeah unfortunately the vast number of different Xcode versions and configurations means most issues like this go unsolved. Without some way to reproduce it (which is unlikely given the number of configurations), I have little hope of finding the bug.

That said, if _you_ can reproduce it, and you feel like trying to debug Ingredients, then pointers and patches are always welcome :)
