### ISSUE TITLE
Incorrect parsing/display of lists within method documentations.

### ISSUE THREAD

**Issue by regexident** [atg/Ingredients#9]
Reproduce by:
1. Search for "indexOfObject:inSortedRange:options:usingComparator:" in Ingredients
2. Compare paragraphs of method's chapter "Returns" (right above "Special Considerations") with those of [Apple's documentation pages](http://developer.apple.com/library/ios/#documentation/Cocoa/Reference/Foundation/Classes/NSArray_Class/NSArray.html%23//apple_ref/occ/instm/NSArray/indexOfObject:inSortedRange:options:usingComparator:)
3. Notice unordered list paragraphs being omitted in Ingredient's documentation display

**Comment by atg** [comment]
Fixed

**Comment by regexident** [comment]
Thanks, great!
